---
# tasks file for roles/tomcat

- name: install tomcat
  yum:
    name: tomcat
    state: present

- name: start and enable tomcat
  service: 
    name: tomcat
    enabled: yes
    state: started

- name: create tomcat directory
  file:
    dest: /usr/share/tomcat/webapps/ansible
    state: directory

- name: copy index.html to tomcat /usr/share/tomcat/webapps/ansible/
  template:
    src: index.html.j2
    dest:  /usr/share/tomcat/webapps/ansible/index.html
    mode: 0644
  notify: restart_tomcat
