---
# tasks file for roles/tomcat

- name: install tomcat
  yum:
    name: "{{ tomcat_pkg }}"
    state: present

- name: start and enable tomcat
  service: 
    name: "{{ tomcat_svc }}"
    enabled: yes
    state: started

- name: create tomcat directory
  file:
    dest: "{{ tomcat_dest }}"
    state: directory

- name: copy index.html to tomcat /usr/share/tomcat/webapps/ROOT/
  template:
    src: index.html.j2
    dest:  "{{ tomcat_dest }}/index.html"
    mode: 0644
  notify: restart_tomcat
