---
# tasks file for postgres

- name: install postgres
  yum: 
    name: "{{ item }}"
    state: present
  loop: "{{ pg_pkg }}"


- name: check postgres stat
  find:
    paths: "{{ pg_data_dir }}"
  register: pg_dir


- name: initialize postgres
  command: "postgresql-setup initdb"
  when: pg_dir.matched == 0
#  notify: restart postgres


- name: turn on postgres starts at boot
  command: chkconfig postgresql on 
  when: pg_dir.matched == 0


- name: start and enable postgres
  service:  
    name: "{{ pg_svc }}"
    enabled: yes
    state: started
