---
# tasks file for postgres

- name: install postgres
  yum: 
    name: "{{ item }}"
    state: present
  loop: "{{ pg_pkg }}"


- name: check postgres stat
  find:
    paths: "{{ pg_data_dir }}"
  register: pg_dir


- name: initialize postgres
  command: "postgresql-setup initdb"
  when: pg_dir.matched == 0
#  notify: restart postgres


- name: turn on postgres starts at boot
  command: chkconfig postgresql on 
  when: pg_dir.matched == 0


- name: start and enable postgres
  service:  
    name: "{{ pg_svc }}"
    enabled: yes
    state: started

- name: create database
  become_user: postgres  
  postgresql_db:
    name: "{{ db['name']}}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: create user
  become_user: postgres
  postgresql_user: 
    db: "{{ db['name'] }}"
    name: "{{ db['user'] }}"
    password: "{{ db['password'] }}"
    priv: ALL
    state: present
